sudo: false

language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.8
      env: COMPILER_VER=-4.8

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: COMPILER_VER=-5

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env: COMPILER_VER=-6

    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.5
          packages:
            - clang-3.5
            - llvm-3.5-dev    # for LLVMgold.so
      env: COMPILER_VER=-3.5

    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
            - llvm-3.7-dev    # for LLVMgold.so
      env: COMPILER_VER=-3.7

    - os: osx
      compiler: clang

    - os: osx
      osx_image: xcode6.4
      compiler: clang

    - os: osx
      osx_image: xcode8
      compiler: clang

install:
  - export CXX="$CXX$COMPILER_VER"
  - export CC="$CC$COMPILER_VER"
  - $CXX --version
  - $CC --version

script: make
