sudo: false

language: cpp

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

script: make

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - if [ "$CXX" = "clang++" ] && [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
  - $CXX --version

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.7
    packages:
    - gcc-4.8
    - g++-4.8
    - clang-3.7
    - llvm-3.7-dev    # for LLVMgold.so
